#!/bin/bash
#
# Kancalar için test

source test-ilkle
pushd "$urtotm_projeDizini" >& /dev/null
# pre-commit # ok - 2023-12-06 17:24
# echo "pre-commit çıkış kodu: $?"
# 
post-commit # ok - 2023-12-06 17:24

# post-merge git komutları çalıştırdığı için proje dizininden çalıştırılmalı
post-merge # ok - 2023-12-06 17:24
popd >& /dev/null
